// <auto-generated />
namespace OnlineAuction.EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class BlogType : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201210200759496_BlogType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soy+XZbHMj9fTljAZnz77KD0ui4zweJ2X5++J1M5DIPWR7Y5RWazK/N2b61XOvRLc66bNF6/brF03362z1Sqv/TfonZd1RR+21/rCT2blOv8oBYjPPnpy3dLvL9ZlmU1K+vs8Kxv64K7f512vU//zUyJSe+2h8qSsLvBnp//fK78OPvBQepWf67tnT8Ne0W/3xe5I8I4M42zZ3tuLjGP16aPXbVXnn+fLvM7afPYya9u8JhY5m+WMvk7Jo9Wnt5uVh3d39jArd7PlsiKi0yz3EO+gCbK8nld1iz8Nxq/bmnj4o/RZ8S6fPc+XF+3cYv1F9s58Qj1+lH61LIjl3ag2Tle8/yd1kZ+/Z9/0q9d3W6+DruXvm3v+qqnzmydqMxyfx+0gSJ7GMea/iZsd2/aZmSS9zUh+a+04kOanE3xNbNPhb3n1dd52xSB1XSm+7qsYTrZ3p2DuioYxmujugCp6/AWNnebUU036Sfpa9NLJ9uv31z4LgXF32gRKqIOt7YkkLbvIO99S14Tps6Ju2qdZm00yzMjJbNFr9n60Np1u0jyBjjIv4PfI5JKqdrPTgeKo+YwGuCCseKw6UkJmGAF++fU0K7M6orxOqnK9WA4pwE1vd3SKD6jz1fvBVD3Rhacfvx8sI/ldYObzKDS1NTcqgIEpvNEabkZbbaOPcdh1FGdjIA2wPvvc7fBPl009paQtO6awy/ebtEe3ie3dapGOtnisknuzd9MTZWnyUUpDvyxmEGOh1xgNxq9/UXlSFpBi2+CLbFmc5037pnqbL9m+HXx9F8ka46aZlREV9f8K36TA8G/0Qt7TIkZ9isusns6zuu9AfA3ggcOwVMhbi+zdnQ93Apgi74lTzAVoi+X1zbDez+L3jdWAAXofYy9S8tlHs0lFuAumH+wK9IX28V0/cHn8NG+KCwcCYcwyZ03pgJo2Z8vzylCcBudjZJp0JuSLvM1mRKPjui3Os2lLX0/zpmHHktXoZx+dLib57Gz55bpdrdvjpskXk/LaH+/ju5v7Z38nxPnxlyv85Wmprz8EQrOgIeRfLp+si3Jm8X4WYaIBEGAXFWvCihxrAndxbSG9qJa3BKTke5qv8iWUwpucTAoBa75cvs4u82HcbqZhSLHHT4vsos4WPgXlEyNpGYyZ64I68N9w/dGfxK4UNR/9PwEAAP//9dTHhqoPAAA="; }
        }
    }
}
