// <auto-generated />
namespace OnlineAuction.EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class BlogType : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201209220331479_BlogType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soy+XZbHMj9fTljAZnz77KD0ui4zweJ2X5++J1M5DIPWR7Y46PCXE2us316ucOyWw7XqWL1u/ETX7vfLr4AP66GVdrfK6vX6Vn+urZ08/Su+G793tvmhf895B7/Tbsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmpUzIErYKxUerT69HSEe3t3ZAyHuZstl1WYgbA/xDprHF/kgnm29zm96H/8aAK/bmrjto/RZ8S6fPc+XF+3cDvaL7J35hH79KP1qWRBz2k42dfr4rpvLjTP8pKwu8OePpjhAE2R5Pa/q9mvMFfXozZV+3xvmzf0/qYv8/D37fl8+iff8VVPnN0/U7fmNVFybkeKqtY9AjT2d4Ou+lpFXX+dtRxelrifRe2P7TWdkXQiW1/sg3FexUVn8nW6+K8rZKPG7A1r88RfZakUT52l1/SR9LSr9ZPv1+yvuhcC4O20i+ttia3siccou8s631DVh+qyom/Zp1maTDHN6Mlv0mr3fbJlONxiQQA+Z9vg9wh1k5Oz8doA4Wj6j4S2oBY9Ux0moDHbP776eZmVWR9TTSVWuF8shFbfpbTYM/uv8we3fF2XjA5BP+hAe3+0MvUtgTx61ZUdRdyfsVtMZtxbvO59DUG4xocOv/uzMaMcO+IA6X70fTNXtXXj68fvBMtq6C8x8/kPmnp7S7DaxvVvl2VGSj1VhBZqUKdD1h3saTJp8lBKZLosZtNfr66bNF2M0GL/+ReVJWbCpMA2+yJbFed60b6q3+ZJt98HXd6qto9E0s/L/pZ51gdHf6GC9p7viecQM//1cDhEgeX15mdXTeVZvLbJ3d/4/7+P+rBA76psq2fqO6NcAHjie7zEhcWihM9lhjw92Jfs+TIiQVVS39yJFh3z20WxSEdaCp37ZfDM+ZqyHD/ZA+0rz8V0/1fD4ad4UFw4EEg/LnI2yA2ranC3PKzOXNDgfI9OkM9Vf5G02ozk4rtviPJu29PU0bxoOWn4yK9fU5HQxyWdnyy/X7WrdHjdNvpiU1/54H9/d3D+72SHOj79c4S/PSnz9IRCaBQ0h/3L5ZF2UM4v3swiTDoAAO6qoE1YUtBG4i2sL6UW1vCUgJd/TfJUvwXlv8sWqJGDNl8vX2WU+jNvNNAwp9vhpkV3U2cKnoHxiJCajnr0uqAP/Ddcf/UnsSnmuo/8nAAD//1NeIpVcEwAA"; }
        }
    }
}
