// <auto-generated />
namespace OnlineAuction.EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Student : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207060123183_Student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soy+XZbHMj9fTljAZnz77KD0ui4zweJ2X5++J1M5DIPWR7Y46PCXE2us316ucOyWw7XqWL1u/ETX7vfLr4AP66GVdrfK6vX6Vn+urZ08/Su+G793tvmhf895B7/Tbsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmpUzIErYKxUerT69HSEe3t3ZAyHuZstl1WYgbA/xDprHF/kgnm29zm96H/8aAK/bmrjto/RZ8S6fPc+XF+3cDvaL7J35hH79KP1qWRBz2k42dfr4rpvL/gwTy7UZMVKtCAVs9XSCr/uzLq++ztsOb6SuJ+HDsf0mhpHt2/H5XWF0IxB3ByTi8RfZakXE8iREP0lfi3icbL9+fyFYCIy70yYiCxZb2xNxX3aRd76lrgnTZ0XdtE+zNptkmL6T2aLX7P0obTrdIIyB1Jr2+D0ys6Qw7Nx0gDhaPqPhLagFj1THSagMds/vvp5mZVZHpPmkKteL5ZBG2PQ2C5n/On9w+/dFyHwA8kkfwuO7naF3CezJkrbs6LXuhG1i+24T27tl/w6bP1aWu9k69HhQmnyUEmkuixn47/V10+aLMRqMX/+i8qQsWFBNgy+yZXGeN+2b6m0OS0ci8vVNjNWsTTMr/19qZwqM/kaL0jNDt7YPDP/rW4flZVZP51m9tcje3fkmNX5fXX2wshdm++yj2aQi9AVN/bL52qagz/uP7/r+0+OneVNcOBDwppY5azsH1LQ5W55Xhtg0NB8j06QzF1/kbTYjCh3XbXGeTVv6epo3DVvsn8zKNTU5XUzy2dnyy3W7WrfHTZMvJuW1P97Hdzf3z/YuxPnxlyv85Qn71x8CoVnQEPIvl0/WRTmzeD/rc/IQCDCLigdhRR4Lgbu4tpBeVMtbAlLyPc1X+RJ88SZfrEoC1ny5fJ1d5sO43UzDkGKPnxbZRZ0tfArKJ4afM+rZ64I68N9w/dGfxK7kvB/9PwEAAP//r4xiLjEMAAA="; }
        }
    }
}
